import { Achievement, Condition } from '@cruncheevos/core';

export const address = {
  deathtollHealth: 0x08a5,
  goatHerb: 0x1a5f,
  bottleGrass: 0x1a67,
  lisaDreamGate: 0x1ae4,
  inventoryOffset: 0x1b1d,
  magicBell: 0x1b35,
  gems: 0x1b66,
  level: 0x1b6a,
  exp: 0x1b78,
  skyCreatures: 0x1b82,
  curHp: 0x1b88,
  nameCheck: 0x1b92,
  mapId: 0x1c6a,
};

type SoulCheevo = {
  title: string;
  type?: Achievement.Type;
  desc: string;
  size: Condition.Size;
  map: number;
};

export const soulCheevoData: SoulCheevo[] = [
  {
    title: 'I Used To Live Up in the Sky',
    type: 'progression',
    desc: 'bring magic back to this world',
    size: 'Bit0',
    map: 0x0d,
  },
  { title: 'I Light Up the Darkness', desc: 'bring light to the world', size: 'Bit1', map: 0x16 },
  { title: 'I Will Protect You', desc: 'protect all creatures', size: 'Bit2', map: 0x29 },
  { title: 'They Need Doors in Heaven, Too', desc: 'reveal hidden enemies', size: 'Bit3', map: 0x52 },
  { title: 'I Know All of the Invisible Passages', desc: 'reveal the truth', size: 'Bit4', map: 0x65 },
];

type CommonItemCheevo = {
  id?: number;
  type?: Achievement.Type;
  title: string;
  points: number;
  desc: string;
  value: number;
  map: number;
};

export const stoneCheevoData: CommonItemCheevo[] = [
  {
    type: 'progression',
    title: 'Grass Valley',
    points: 5,
    desc: "Defeat Deathtoll's forces in Grass valley and get the Brown Stone.",
    value: 0x3a,
    map: 0x04,
  },
  {
    title: "Turbo's Resting Place",
    type: 'progression',
    points: 5,
    desc: "Defeat Deathtoll's forces at GreenWood and receive the Green Stone.",
    value: 0x3b,
    map: 0x15,
  },
  {
    title: 'The Underwater Level',
    type: 'progression',
    points: 5,
    desc: "Defeat Deathtoll's forces at St. Elle's and receive the Blue Stone.",
    value: 0x3c,
    map: 0x29,
  },
  {
    title: "Nome Isn't a Gnome",
    type: 'progression',
    points: 5,
    desc: "Defeat Deathtoll's forces at The Mountain of Souls and receive the Silver Stone.",
    value: 0x3d,
    map: 0x3d,
  },
  {
    title: "Doctor's Doll",
    type: 'progression',
    points: 5,
    desc: "Defeat Deathtoll's forces at Doctor Leo's laboratory and get the Purple Stone.",
    value: 0x3e,
    map: 0x53,
  },
  {
    title: "Sold Everyone's Soul But His Own",
    type: 'progression',
    points: 5,
    desc: "Defeat Deathtoll's forces at Magridd Castle and get the Black Stone.",
    value: 0x3f,
    map: 0x65,
  },
  {
    title: 'Now Go and Save the World',
    points: 2,
    desc: "Get the Sword of Life. You're on a mission from God.",
    value: 0x01,
    map: 0x0d,
  },
  { title: 'Food for War', points: 2, desc: 'Trade the Delicious Seeds for the Psycho Sword.', value: 0x02, map: 0x18 },
  {
    title: 'Sacrifice of Fire',
    points: 2,
    desc: 'Walk across magma and get the Critical Sword.',
    value: 0x03,
    map: 0x30,
  },
  {
    title: "Gettin' Lucky",
    type: 'progression',
    points: 2,
    desc: 'Find the Lucky Blade and those sweet, sweet GEMs.',
    value: 0x04,
    map: 0x47,
  },
  {
    title: 'Finally!',
    type: 'progression',
    points: 3,
    desc: 'Get the Zantetsu Sword. Now go back and seal those lairs!',
    value: 0x05,
    map: 0x51,
  },
  {
    title: 'Ghost Buster',
    type: 'progression',
    points: 4,
    desc: 'Find the Sprit Sword and put those tortured souls to rest...THE HARD WAY.',
    value: 0x06,
    map: 0x66,
  },
  {
    title: 'Like a Vampire',
    points: 5,
    desc: 'Convince a certain fairy to give you the Recovery Sword.',
    value: 0x07,
    map: 0x01,
  },
  {
    title: 'You Cannot, but You May',
    type: 'progression',
    points: 5,
    desc: "Wrest the Soul Blade from Deathtoll's grip.",
    value: 0x08,
    map: 0x7b,
  },
  {
    title: "The Vine's Gift",
    points: 2,
    desc: "Get the Iron Armor. It's better than nothing!",
    value: 0x09,
    map: 0x03,
  },
  {
    title: 'Dendroid Dreams',
    points: 2,
    desc: "Get the Ice Armor. Hot metal won't bother you now!",
    value: 0x0a,
    map: 0x15,
  },
  {
    title: "I'll Never Let You Go, Jack",
    points: 2,
    desc: "Get the Bubble Armor. Hopefully it's not carbon dioxide.",
    value: 0x0b,
    map: 0x29,
  },
  {
    title: "It's Too Cold to Wear",
    points: 2,
    desc: 'Find the Magic Armor buried in the snow.',
    value: 0x0c,
    map: 0x3f,
  },
  { title: 'Invincible (for a second)', points: 3, desc: 'Get the Mystic Armor.', value: 0x0d, map: 0x51 },
  {
    title: 'Not Really Invincible',
    points: 4,
    desc: 'Get the Light Armor. It is invincibility, after a fashion.',
    value: 0x0e,
    map: 0x58,
  },
  {
    title: 'DANGER ZONE',
    points: 5,
    desc: 'Does Leo still dream of regret? Get the Elemental Mail.',
    value: 0x0f,
    map: 0x65,
  },
  {
    title: 'Space Suit',
    type: 'progression',
    points: 5,
    desc: "Get the Soul Armor so you don't violently decompress.",
    value: 0x10,
    map: 0x7a,
  },
  {
    title: 'Legacy of Monmo',
    points: 3,
    desc: 'Help two wandering spririts remember love and get the Shield Bracelet.',
    value: 0x36,
    map: 0x16,
  },
  {
    title: 'Honey, You Got Real Ugly',
    points: 5,
    desc: "Find the awful queen's Invulnerable...er...Super Bracelet.",
    value: 0x37,
    map: 0x65,
  },
  { title: 'It Was Just Sitting There...', points: 3, desc: 'Get the Power Bracelet.', value: 0x35, map: 0x34 },
  { title: 'Four Way', points: 5, desc: 'Find the "Light" Arrow magic.', value: 0x12, map: 0x1f },
  { title: 'Purple Bombs', points: 5, desc: 'Get the Magic Flair.', value: 0x13, map: 0x29 },
  { title: 'You Spin Me...', points: 5, desc: 'Find the Rotator magic for those pesky bats.', value: 0x14, map: 0x47 },
  {
    title: 'Rattus Rattus',
    points: 5,
    desc: 'Convince the nice rat to give you the Spark Bomb magic.',
    value: 0x15,
    map: 0x54,
  },
  {
    title: 'By Fire, Be Purged!',
    points: 5,
    desc: 'Light up the darkness and get the Flame Pillar magic.',
    value: 0x16,
    map: 0x20,
  },
  {
    title: 'It Will Come...',
    points: 5,
    desc: 'Get the Tornado magic. It smells like paint...',
    value: 0x17,
    map: 0x08,
  },
  { title: 'Garuda', type: 'progression', points: 5, desc: 'Get the Phoenix magic.', value: 0x18, map: 0x3d },
  { title: 'Dionysis', points: 5, desc: "Climb and dig to find The Master's Emblem A.", value: 0x2a, map: 0x01 },
  {
    title: 'Ophthalmitis',
    points: 5,
    desc: "Have someone help you see The Master's Emblem B.",
    value: 0x2b,
    map: 0x68,
  },
  {
    title: 'Ninkilim',
    points: 5,
    desc: "Convince a squirrel to give you The Master's Emblem C.",
    value: 0x2c,
    map: 0x18,
  },
  {
    title: 'Prohodna',
    points: 5,
    desc: "Make a dolphin's dreams come true and get The Master's Emblem D.",
    value: 0x2d,
    map: 0x2b,
  },
  { title: 'Nerites', points: 5, desc: "Get The Master's Emblem E from a hidden snail.", value: 0x2e, map: 0x3d },
  {
    title: 'Teonanacatl',
    points: 5,
    desc: "Get The Master's Emblem F with some fungal assistance.",
    value: 0x2f,
    map: 0x42,
  },
  { title: 'Hestia', points: 5, desc: "Find the household Master's Emblem G.", value: 0x30, map: 0x51 },
  {
    title: 'Jahbulon',
    points: 5,
    desc: "Find The Master's Emblem H that the stone mason hid.",
    value: 0x31,
    map: 0x65,
  },
  {
    title: 'Merlin, Gandalf, Dumbledore, YOU',
    points: 5,
    desc: 'With the help of a deer and a fairy, get the Magic Bell.',
    value: 0x40,
    map: 0x15,
  },
  {
    title: '3spooky5me',
    type: 'progression',
    points: 5,
    desc: "Get the Red-Hot Mirror. Please don't sneak up behind that bird anymore.",
    value: 0x32,
    map: 0x15,
  },
  {
    title: 'A Phoenix Needs Its Ball',
    type: 'progression',
    points: 5,
    desc: 'Get the Red-Hot Ball from outerrrrrr spaaaaace.',
    value: 0x33,
    map: 0x79,
  },
  {
    title: 'The Phoenix Resides on the Stick',
    type: 'progression',
    points: 5,
    desc: 'Save the Red-Hot Stick from the metal apes.',
    value: 0x34,
    map: 0x29,
  },
];

export type Access = {
  size: Condition.Size;
  addr: number;
};

type SealCheevo = {
  title: string;
  desc: string;
  maps: number[];
  lairs: Access[];
  target: number;
};

export const sealCheevoData: SealCheevo[] = [
  {
    title: 'Vines and Bridges and Widows, Oh My',
    desc: 'in the west screen of the Underground Castle',
    maps: [0x01, 0x05],
    lairs: [
      { addr: 0x1ade, size: 'Bit1' },
      { addr: 0x1ade, size: 'Bit2' },
      { addr: 0x1ade, size: 'Bit3' },
      { addr: 0x1ade, size: 'Bit4' },
      { addr: 0x1ade, size: 'Bit5' },
      { addr: 0x1ade, size: 'Bit6' },
      { addr: 0x1ade, size: 'Bit7' },
      { addr: 0x1adf, size: 'Bit0' },
      { addr: 0x1adf, size: 'Bit2' },
      { addr: 0x1adf, size: 'Bit3' },
      { addr: 0x1adf, size: 'Bit4' },
      { addr: 0x1adf, size: 'Bit5' },
      { addr: 0x1adf, size: 'Bit6' },
      { addr: 0x1ae3, size: 'Bit1' },
    ],
    target: 14,
  },
  {
    title: 'Sleepy Girls and Screaming Men',
    desc: 'in the east screen of the Underground Castle',
    maps: [0x01, 0x06],
    lairs: [
      { addr: 0x1adf, size: 'Bit7' },
      { addr: 0x1ae0, size: 'Bit0' },
      { addr: 0x1ae0, size: 'Bit1' },
      { addr: 0x1ae0, size: 'Bit2' },
      { addr: 0x1ae3, size: 'Bit2' },
      { addr: 0x1ae0, size: 'Bit6' },
      { addr: 0x1ae0, size: 'Bit4' },
      { addr: 0x1ae4, size: 'Bit0' },
      { addr: 0x1ae4, size: 'Bit1' },
      { addr: 0x1ae0, size: 'Bit5' },
      { addr: 0x1ae0, size: 'Bit7' },
      { addr: 0x1ae1, size: 'Bit0' },
      { addr: 0x1ae1, size: 'Bit1' },
      { addr: 0x1ae1, size: 'Bit2' },
      { addr: 0x1ae3, size: 'Bit0' },
    ],
    target: 15,
  },
  {
    title: 'The Yellow Sign',
    desc: "in Dr. Leo's painting",
    maps: [0x01, 0x07, 0x08, 0x09, 0x0b, 0x0c],
    lairs: [
      { addr: 0x1ae0, size: 'Bit3' },
      { addr: 0x1ae1, size: 'Bit3' },
      { addr: 0x1ae1, size: 'Bit4' },
      { addr: 0x1ae1, size: 'Bit5' },
      { addr: 0x1ae1, size: 'Bit6' },
      { addr: 0x1ae1, size: 'Bit7' },
      { addr: 0x1ae2, size: 'Bit0' },
      { addr: 0x1ae2, size: 'Bit1' },
      { addr: 0x1ae2, size: 'Bit2' },
      { addr: 0x1ae2, size: 'Bit3' },
      { addr: 0x1ae2, size: 'Bit4' },
      { addr: 0x1ae2, size: 'Bit5' },
      { addr: 0x1ae3, size: 'Bit3' },
      { addr: 0x1ae3, size: 'Bit4' },
      { addr: 0x1ae3, size: 'Bit6' },
      { addr: 0x1ae3, size: 'Bit7' },
      { addr: 0x1ae4, size: 'Bit3' },
      { addr: 0x1ae4, size: 'Bit4' },
    ],
    target: 18,
  },
  {
    title: 'Craving Critters and Beastie Bedtime',
    desc: 'in Lostside and GreenWood',
    maps: [0x15, 0x16, 0x17, 0x18, 0x19, 0x23, 0x24],
    lairs: [
      { addr: 0x1aa5, size: 'BitCount' },
      { addr: 0x1aa6, size: 'Bit0' },
      { addr: 0x1aac, size: 'Bit4' },
      { addr: 0x1aac, size: 'Bit5' },
    ],
    target: 11,
  },
  {
    title: 'Hungry Squirrels and Friendly Crocs',
    desc: 'in the Water Shrine',
    maps: [0x15, 0x16, 0x17, 0x18, 0x1a, 0x1b, 0x1c],
    lairs: [
      { addr: 0x1aa6, size: 'Bit2' },
      { addr: 0x1aa6, size: 'Bit3' },
      { addr: 0x1aa6, size: 'Bit4' },
      { addr: 0x1aa6, size: 'Bit5' },
      { addr: 0x1aa6, size: 'Bit6' },
      { addr: 0x1aa6, size: 'Bit7' },
      { addr: 0x1aa7, size: 'BitCount' },
      { addr: 0x1aa8, size: 'Bit1' },
      { addr: 0x1aa8, size: 'Bit2' },
    ],
    target: 16,
  },
  {
    title: 'Heat of the Grave',
    desc: 'in the Fire Shrine',
    maps: [0x15, 0x16, 0x17, 0x18, 0x1d, 0x1e, 0x1f],
    lairs: [
      { addr: 0x1aa8, size: 'Bit3' },
      { addr: 0x1aa8, size: 'Bit4' },
      { addr: 0x1aa8, size: 'Bit5' },
      { addr: 0x1aa8, size: 'Bit6' },
      { addr: 0x1aa8, size: 'Bit7' },
      { addr: 0x1aa9, size: 'BitCount' },
      { addr: 0x1aaa, size: 'Bit0' },
      { addr: 0x1aaa, size: 'Bit1' },
      { addr: 0x1aaa, size: 'Bit2' },
      { addr: 0x1aaa, size: 'Bit3' },
      { addr: 0x1aaa, size: 'Bit4' },
      { addr: 0x1aac, size: 'Bit3' },
      { addr: 0x1aac, size: 'Bit6' },
    ],
    target: 20,
  },
  {
    title: 'Bringer of Light',
    desc: 'in the Light Shrine',
    maps: [0x15, 0x16, 0x17, 0x18, 0x20, 0x21, 0x22],
    lairs: [
      { addr: 0x1aaa, size: 'Bit5' },
      { addr: 0x1aaa, size: 'Bit6' },
      { addr: 0x1aaa, size: 'Bit7' },
      { addr: 0x1aab, size: 'BitCount' },
      { addr: 0x1aa6, size: 'Bit1' },
      { addr: 0x1aac, size: 'Bit2' },
      { addr: 0x1aac, size: 'Bit0' },
      { addr: 0x1aac, size: 'Bit1' },
      { addr: 0x1aa8, size: 'Bit0' },
      { addr: 0x1aa4, size: 'Bit7' },
      { addr: 0x1aa4, size: 'Bit6' },
    ],
    target: 18,
  },
  {
    title: 'Lots of Sea Dwelling Mammals',
    desc: "in Southerta and the Seabed of St Elle's",
    maps: [0x29, 0x2a, 0x2e],
    lairs: [
      { addr: 0x1aad, size: 'Bit2' },
      { addr: 0x1aad, size: 'Bit3' },
      { addr: 0x1aae, size: 'Bit0' },
      { addr: 0x1aae, size: 'Bit1' },
      { addr: 0x1aae, size: 'Bit2' },
      { addr: 0x1aae, size: 'Bit5' },
      { addr: 0x1aaf, size: 'Bit0' },
      { addr: 0x1aae, size: 'Bit7' },
      { addr: 0x1ab1, size: 'Bit1' },
      { addr: 0x1ab1, size: 'Bit2' },
      { addr: 0x1ab1, size: 'Bit3' },
      { addr: 0x1ab1, size: 'Bit4' },
      { addr: 0x1ab1, size: 'Bit5' },
      { addr: 0x1ab1, size: 'Bit6' },
      { addr: 0x1ab1, size: 'Bit7' },
      { addr: 0x1ab2, size: 'Bit0' },
      { addr: 0x1ab2, size: 'Bit1' },
      { addr: 0x1ab2, size: 'Bit2' },
      { addr: 0x1ab2, size: 'Bit3' },
      { addr: 0x1ab2, size: 'Bit4' },
      { addr: 0x1ab2, size: 'Bit5' },
      { addr: 0x1ab6, size: 'Bit1' },
      { addr: 0x1ab6, size: 'Bit2' },
      { addr: 0x1ab6, size: 'Bit3' },
    ],
    target: 24,
  },
  {
    title: 'Magma and Water',
    desc: 'at Rockbird and Durean',
    maps: [0x29, 0x2c, 0x2f, 0x30],
    target: 32,
    lairs: [
      { addr: 0x1ab0, size: 'BitCount' },
      { addr: 0x1ab1, size: 'Bit0' },
      { addr: 0x1ab2, size: 'Bit7' },
      { addr: 0x1ab2, size: 'Bit6' },
      { addr: 0x1ab4, size: 'Bit0' },
      { addr: 0x1ab3, size: 'Bit7' },
      { addr: 0x1ab3, size: 'Bit0' },
      { addr: 0x1ab3, size: 'Bit2' },
      { addr: 0x1ab3, size: 'Bit6' },
      { addr: 0x1ab3, size: 'Bit4' },
      { addr: 0x1ab3, size: 'Bit3' },
      { addr: 0x1ab4, size: 'Bit4' },
      { addr: 0x1ab4, size: 'Bit5' },
      { addr: 0x1ab3, size: 'Bit1' },
      { addr: 0x1ab4, size: 'Bit3' },
      { addr: 0x1ab4, size: 'Bit2' },
      { addr: 0x1aad, size: 'Bit5' },
      { addr: 0x1ab4, size: 'Bit1' },
      { addr: 0x1aaf, size: 'Bit7' },
      { addr: 0x1aaf, size: 'Bit1' },
      { addr: 0x1aaf, size: 'Bit2' },
      { addr: 0x1aaf, size: 'Bit3' },
      { addr: 0x1aaf, size: 'Bit4' },
      { addr: 0x1aaf, size: 'Bit5' },
      { addr: 0x1aaf, size: 'Bit6' },
    ],
  },
  {
    title: 'A Sound of Thunder',
    desc: 'at Blester and on the Ghost Ship',
    maps: [0x29, 0x2c, 0x31, 0x32, 0x34],
    target: 10,
    lairs: [
      { addr: 0x1ab5, size: 'BitCount' },
      { addr: 0x1ab6, size: 'Bit0' },
      { addr: 0x1ab4, size: 'Bit6' },
    ],
  },
  {
    title: 'Snails and Shrooms (and Gnomes)',
    desc: 'at The Mountain of Souls',
    maps: [0x3d, 0x3e, 0x3f, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47],
    target: 64,
    lairs: [
      { addr: 0x1ab6, size: 'Bit4' },
      { addr: 0x1ab6, size: 'Bit5' },
      { addr: 0x1ab6, size: 'Bit6' },
      { addr: 0x1ab6, size: 'Bit7' },
      { addr: 0x1ab7, size: 'BitCount' },
      { addr: 0x1ab8, size: 'BitCount' },
      { addr: 0x1ab9, size: 'BitCount' },
      { addr: 0x1aba, size: 'BitCount' },
      { addr: 0x1abb, size: 'BitCount' },
      { addr: 0x1abc, size: 'BitCount' },
      { addr: 0x1abd, size: 'BitCount' },
      { addr: 0x1abe, size: 'Bit2' },
      { addr: 0x1abe, size: 'Bit0' },
      { addr: 0x1abe, size: 'Bit1' },
      { addr: 0x1abe, size: 'Bit3' },
    ],
  },
  {
    title: 'Kill Robots to Make Doors!',
    desc: 'in the basement of the Laboratory and Power Plant',
    maps: [0x51, 0x52, 0x53, 0x54, 0x56, 0x57, 0x58],
    target: 43,
    lairs: [
      { addr: 0x1abf, size: 'Bit1' },
      { addr: 0x1abf, size: 'Bit2' },
      { addr: 0x1abf, size: 'Bit3' },
      { addr: 0x1abf, size: 'Bit4' },
      { addr: 0x1abf, size: 'Bit5' },
      { addr: 0x1abf, size: 'Bit6' },
      { addr: 0x1abf, size: 'Bit7' },
      { addr: 0x1ac0, size: 'BitCount' },
      { addr: 0x1ac1, size: 'BitCount' },
      { addr: 0x1ac2, size: 'BitCount' },
      { addr: 0x1ac3, size: 'Bit0' },
      { addr: 0x1ac3, size: 'Bit1' },
      { addr: 0x1ac3, size: 'Bit2' },
      { addr: 0x1ac3, size: 'Bit5' },
      { addr: 0x1ac3, size: 'Bit6' },
      { addr: 0x1ac4, size: 'Bit0' },
      { addr: 0x1ac4, size: 'Bit1' },
      { addr: 0x1ac4, size: 'Bit2' },
      { addr: 0x1ac4, size: 'Bit3' },
      { addr: 0x1ac4, size: 'Bit4' },
      { addr: 0x1ac4, size: 'Bit5' },
      { addr: 0x1ac4, size: 'Bit6' },
    ],
  },
  {
    title: 'Does the Real Town Have So Many Monsters?',
    desc: 'in the town models',
    maps: [0x51, 0x52, 0x53, 0x54, 0x5b, 0x5c],
    target: 29,
    lairs: [
      { addr: 0x1ac4, size: 'Bit7' },
      { addr: 0x1ac5, size: 'Bit0' },
      { addr: 0x1ac5, size: 'Bit1' },
      { addr: 0x1ac5, size: 'Bit3' },
      { addr: 0x1ac5, size: 'Bit4' },
      { addr: 0x1ac5, size: 'Bit5' },
      { addr: 0x1ac5, size: 'Bit6' },
      { addr: 0x1ac5, size: 'Bit7' },
      { addr: 0x1ac6, size: 'Bit0' },
      { addr: 0x1ac6, size: 'Bit1' },
      { addr: 0x1ac6, size: 'Bit2' },
      { addr: 0x1ac6, size: 'Bit3' },
      { addr: 0x1ac6, size: 'Bit4' },
      { addr: 0x1ac6, size: 'Bit5' },
      { addr: 0x1ac6, size: 'Bit7' },
      { addr: 0x1ac7, size: 'BitCount' },
      { addr: 0x1ac8, size: 'Bit0' },
      { addr: 0x1ac8, size: 'Bit1' },
      { addr: 0x1ac8, size: 'Bit2' },
      { addr: 0x1ac8, size: 'Bit3' },
      { addr: 0x1ac8, size: 'Bit4' },
      { addr: 0x1ac8, size: 'Bit5' },
    ],
  },
  {
    title: 'Revenants for Halberdiers',
    desc: 'in the torture chamber and basement of Castle Magridd',
    maps: [0x65, 0x66, 0x67, 0x68, 0x71],
    target: 27,
    lairs: [
      { addr: 0x1ac9, size: 'BitCount' },
      { addr: 0x1aca, size: 'BitCount' },
      { addr: 0x1acb, size: 'BitCount' },
      { addr: 0x1acc, size: 'Bit0' },
      { addr: 0x1acc, size: 'Bit1' },
      { addr: 0x1acc, size: 'Bit2' },
    ],
  },
  {
    title: 'My Left or Your Left?',
    desc: 'in the left tower of Castle Magridd',
    maps: [0x65, 0x6a, 0x6b, 0x6c, 0x71],
    target: 19,
    lairs: [
      { addr: 0x1acc, size: 'Bit3' },
      { addr: 0x1acc, size: 'Bit4' },
      { addr: 0x1acc, size: 'Bit5' },
      { addr: 0x1acc, size: 'Bit6' },
      { addr: 0x1acc, size: 'Bit7' },
      { addr: 0x1acd, size: 'BitCount' },
      { addr: 0x1ace, size: 'Bit0' },
      { addr: 0x1ace, size: 'Bit1' },
      { addr: 0x1ace, size: 'Bit2' },
      { addr: 0x1ace, size: 'Bit3' },
      { addr: 0x1ace, size: 'Bit4' },
      { addr: 0x1ace, size: 'Bit5' },
    ],
  },
  {
    title: 'Everybody Looks Left, You Go Right',
    desc: 'in the right tower of Castle Magridd',
    maps: [0x65, 0x6d, 0x6e, 0x6f, 0x70, 0x71],
    target: 14,
    lairs: [
      { addr: 0x1ace, size: 'Bit6' },
      { addr: 0x1ace, size: 'Bit7' },
      { addr: 0x1acf, size: 'BitCount' },
      { addr: 0x1ad0, size: 'Bit0' },
      { addr: 0x1ad0, size: 'Bit1' },
      { addr: 0x1ad0, size: 'Bit2' },
      { addr: 0x1ad0, size: 'Bit3' },
    ],
  },
  {
    title: 'Space Demons',
    desc: 'in The World of Evil',
    maps: [0x79, 0x7a, 0x7b],
    target: 14,
    lairs: [
      { addr: 0x1ad1, size: 'BitCount' },
      { addr: 0x1ad2, size: 'Bit0' },
      { addr: 0x1ad2, size: 'Bit1' },
      { addr: 0x1ad2, size: 'Bit2' },
      { addr: 0x1ad2, size: 'Bit3' },
      { addr: 0x1ad0, size: 'Bit6' },
      { addr: 0x1ad0, size: 'Bit7' },
    ],
  },
];

export type DamagelessCheevo = {
  id: number;
  badge: string;
  title: string;
  desc: string;
  points: 25 | 50;
  map: number;
  lair: number;
};

export const damagelessData: DamagelessCheevo[] = [
  {
    id: 4868,
    badge: '214220',
    title: 'Hitting Heavy Metal Mantis',
    desc: 'Defeat Metal Mantis without getting hit.',
    points: 25,
    map: 0x0c,
    lair: 0x1020c,
  },
  {
    id: 31331,
    badge: '214221',
    title: 'Stoning the Stone Lion Heads',
    desc: 'Defeat the Stone Lion Heads without getting hit.',
    points: 25,
    map: 0x22,
    lair: 0x10253,
  },
  {
    badge: '214222',
    id: 31449,
    title: 'Flushing the Floating Skull',
    desc: 'Traverse the Ghost Ship and defeat the Floating Skull all without getting hit.',
    points: 25,
    map: 0x32,
    lair: 0x102b9,
  },
  {
    id: 31468,
    badge: '214223',
    title: 'Pushing Poseidon',
    desc: 'Defeat Poseidon without getting hit.',
    points: 25,
    map: 0x44,
    lair: 0x10306,
  },
  {
    id: 31487,
    badge: '214224',
    title: 'Terrorizing the Tin Doll',
    desc: 'Defeat the Tin Doll without getting hit.',
    points: 25,
    map: 0x59,
    lair: 0x10332,
  },
  {
    id: 31552,
    badge: '214225',
    title: 'Defeating the Demon Falcon',
    desc: 'Defeat the Demon Falcon without getting hit.',
    points: 50,
    map: 0x72,
    lair: 0x10398,
  },
];

export type ExpCheevo = {
  title: string;
  type?: Achievement.Type;
  target: number;
  prev: number;
  desc: string;
  points: 5 | 10;
};

export const expData: ExpCheevo[] = [
  {
    title: 'Angelo',
    type: 'progression',
    desc: '10 and become a servant of The Master.',
    prev: 0x09,
    target: 0x10,
    points: 5,
  },
  {
    title: 'Throne',
    type: 'progression',
    desc: '20. Do you feel the power of The Master?',
    prev: 0x19,
    target: 0x20,
    points: 5,
  },
  {
    title: 'Cherub',
    desc: '30 by driving the forces of Deathtoll from this world.',
    prev: 0x29,
    target: 0x30,
    points: 10,
  },
  {
    title: 'Seraph',
    desc: '40 and rebuke the forces of evil.',
    prev: 0x39,
    target: 0x40,
    points: 10,
  },
];

export const rpMapLookup = {
  0x00: 'Grass Valley Shrine',
  0x01: 'Grass Valley Highlands',
  0x02: "the child's Secret Passage",
  0x03: 'the Treasure Room',
  0x04: "the Village Chief's Room",
  0x05: 'Underground Castle West',
  0x06: 'Underground Castle East',
  0x07: "Leo's Paintings 1",
  0x08: "Leo's Paintings 2",
  0x09: "Leo's Paintings 3",
  0x0a: "the tulip's dream",
  0x0b: "Leo's Paintings 4",
  0x0c: 'Metal Mantis',
  0x0d: 'the Trial Room',
  0x0e: "Lisa's dream",
  0x0f: 'the Overworld',
  0x14: 'GreenWood Shrine',
  0x15: 'the Woods of GreenWood',
  0x16: "a Mole's hole",
  0x17: "a squirrel's house",
  0x18: "the Exchanger Squirrel's house",
  0x19: 'Lostside, a marsh',
  0x1a: 'Water Shrine 1F',
  0x1b: 'Water Shrine B1',
  0x1c: 'Water Shrine B2',
  0x1d: 'Fire Shrine 1F',
  0x1e: 'Fire Shrine B1',
  0x1f: 'Fire Shrine B2',
  0x20: 'Light Shrine 1F',
  0x21: 'Light Shrine B1',
  0x22: 'the Elemental Statues',
  0x23: "the bird's dream",
  0x24: "the stump's dream",
  0x28: 'St. Elles Shrine',
  0x29: 'the Seabed Sanctuary',
  0x2a: 'the Seabed of St. Elles (Front)',
  0x2b: 'the Secret Coral Cave',
  0x2c: 'the Secret Prison Cave',
  0x2d: "a dolphin's dream",
  0x2e: 'Southerta',
  0x2f: 'the shore reef of Rockbird',
  0x30: 'Durean',
  0x31: 'Blester',
  0x32: 'the Floating Skull',
  0x33: "Servas' dream",
  0x34: 'the Seabed of St. Elles (Back)',
  0x3c: "the Soul's Sanctuary",
  0x3d: 'Soul of Mountain House',
  0x3e: 'the Northern Mountain',
  0x3f: "Aurora's Ridge",
  0x40: "an old man's dream",
  0x41: 'a passage to Lune',
  0x42: 'Lune Lake',
  0x43: "a mushroom's dream",
  0x44: 'Poseidon',
  0x45: 'the top of Snow Mountain',
  0x46: 'an ice hill',
  0x47: 'the ice field of Laynole',
  0x50: 'The Laboratory Shrine',
  0x51: "Leo's Laboratory 1F",
  0x52: "Leo's Laboratory 2F",
  0x53: "Leo's Attic",
  0x54: 'A mice nest',
  0x55: "a cat's Dream",
  0x56: "Leo's Laboratory B1",
  0x57: "Leo's Laboratory B2",
  0x58: 'the power plant',
  0x59: 'Tin Doll',
  0x5a: "a plant's dream",
  0x5b: 'Town Model 1',
  0x5c: 'Town Model 2',
  0x64: 'Magridd Castle Shrine',
  0x65: 'Castle of King Magridd',
  0x66: 'the torture chamber',
  0x67: 'Magridd Castle B1',
  0x68: 'Magridd Castle B2',
  0x6a: 'the left tower 1F',
  0x6b: 'the left tower 2F',
  0x6c: 'the left tower prison',
  0x6d: 'the right tower 1F',
  0x6e: 'the right tower 2F',
  0x6f: 'the right tower 3F',
  0x70: 'the airship docks corridor',
  0x71: 'the airship docks',
  0x72: 'the Demon Falcon',
  0x73: "Soldier's Dream",
  0x78: 'The Evil World Shrine',
  0x79: 'World of Evil 1',
  0x7a: 'World of Evil 2',
  0x7b: 'Dazzling Space',
  0x7c: 'Deathtoll',
  0x7d: "Deathtoll's Demon Form",
};

export const rpPurposeLookup = {
  0x00: 'recover strength',
  0x14: 'recover strength',
  0x28: 'recover strength',
  0x3c: 'recover strength',
  0x50: 'recover strength',
  0x64: 'recover strength',
  0x78: 'recover strength',
  0x01: 'chat with locals',
  0x02: 'chat with locals',
  0x03: 'chat with locals',
  0x04: 'chat with locals',
  0x15: 'chat with locals',
  0x16: 'chat with locals',
  0x17: 'chat with locals',
  0x18: 'chat with locals',
  0x29: 'chat with locals',
  0x3d: 'chat with locals',
  0x51: 'chat with locals',
  0x52: 'chat with locals',
  0x53: 'chat with locals',
  0x54: 'chat with locals',
  0x65: 'chat with locals',
  0x0a: 'gain information',
  0x0e: 'gain information',
  0x23: 'gain information',
  0x24: 'gain information',
  0x2d: 'gain information',
  0x33: 'gain information',
  0x40: 'gain information',
  0x43: 'gain information',
  0x55: 'gain information',
  0x5a: 'gain information',
  0x73: 'gain information',
};

export const rpActionLookup = {
  0x00: 'resting at',
  0x14: 'resting at',
  0x28: 'resting at',
  0x3c: 'resting at',
  0x50: 'resting at',
  0x64: 'resting at',
  0x78: 'resting at',
  0x01: 'exploring',
  0x02: 'exploring',
  0x03: 'exploring',
  0x04: 'exploring',
  0x15: 'exploring',
  0x16: 'exploring',
  0x17: 'exploring',
  0x18: 'exploring',
  0x29: 'exploring',
  0x3d: 'exploring',
  0x51: 'exploring',
  0x52: 'exploring',
  0x53: 'exploring',
  0x54: 'exploring',
  0x65: 'exploring',
  0x0a: 'peering into',
  0x0e: 'peering into',
  0x23: 'peering into',
  0x24: 'peering into',
  0x2d: 'peering into',
  0x33: 'peering into',
  0x40: 'peering into',
  0x43: 'peering into',
  0x55: 'peering into',
  0x5a: 'peering into',
  0x73: 'peering into',
  0x0c: 'fighting',
  0x22: 'fighting',
  0x32: 'fighting',
  0x44: 'fighting',
  0x59: 'fighting',
  0x72: 'fighting',
  0x7c: 'fighting',
  0x7d: 'fighting',
};
